### ISSUE TITLE
couchbase-operator-0.1.2.tgz : 404 Not Found

### ISSUE THREAD

**Issue by taylorjstacey** [couchbase-partners/helm-charts#1]
Running `helm install couchbase/couchbase-operator` now results in the following message.

> Error: failed to download "couchbase/couchbase-operator" (hint: running `helm repo update` may help)

If I attempt to install the couchbase-operator chart through Terraform, it reveals the following error:

> Failed to fetch https://github.com/couchbase-partners/helm-charts/couchbase-operator-0.1.2.tgz : 404 Not Found

That file appears to be located on the gh-pages branch.

**Comment by tahmmee** [comment]
Ok, should be working now, the url from the index was pointing directly to github instead of the hosted path.

**Comment by taylorjstacey** [comment]
Everything is working perfectly now. Thanks!
