### ISSUE TITLE
disable tls when adminConsoleServiceType is LoadBalancer 

### ISSUE THREAD

**Issue by zijin-m** [couchbase-partners/helm-charts#11]
when i set `adminConsoleServiceType` to `LoadBalancer`, then helm upgrade,i get errors below,hot to disbale tls

`Error: UPGRADE FAILED: cannot patch "couchbase" with kind CouchbaseCluster: admission webhook "couchbase-couchbase-admission-controller.couchbase.svc" denied the request: validation failure list:
spec.tls in body is required`

**Comment by tahmmee** [comment]
Hi @zijin-m , external LoadBalancer requires TLS enabled try:
```
helm upgrade <release-name>  --set tls.generate=true couchbase/couchbase-operator
```

**Comment by zijin-m** [comment]
@tahmmee  thx,but get this
`Error: UPGRADE FAILED: cannot patch "couchbase" with kind CouchbaseCluster: admission webhook "couchbase-couchbase-admission-controller.couchbase.svc" denied the request: validation failure list:
certificate cannot be verified for zone: x509: certificate is valid for localhost, *.couchbase.couchbase.svc, *.couchbase.couchbase, *.couchbase, *.couchbase-srv.couchbase.svc, *.couchbase-srv.couchbase, *.couchbase-srv, couchbase-srv.couchbase.svc, couchbase-srv.couchbase, couchbase-srv, not host.example.com`

**Comment by tahmmee** [comment]
Did some more testing with this and wasn't able to reproduce this error.  Can you share more about the original state of cluster...ie what values were used at time of install, and also the override values used during upgrade.
I'm also assuming the upgrade is across same major versions of the chart 2.0.x?

Here's an example of what should work
```
helm upgrade default --set cluster.networking.adminConsoleServiceType=LoadBalancer --set tls.generate=true --set cluster.networking.dns.domain=example.com couchbase/couchbase-operator
```

**Comment by zijin-m** [comment]
@tahmmee  
I installed it using the domain name `example.com` for the first time, and then I changed it to `test.example.com`.The error occurred `Error: UPGRADE FAILED`.
 It seems that tls did not regenerate the certificate. Just delete it use `helm delete` and recreate it and It succeeded.
