### ISSUE TITLE
Couchbase nodes a being scheduled on the same nodes

### ISSUE THREAD

**Issue by 8tomat8** [couchbase-partners/helm-charts#16]
**Context:**
In the CRD there is a special instruction, which [according to the documentation](https://docs.couchbase.com/operator/2.0/concept-scheduling.html#pod-isolation), should create inner pod anti-affinity rules, so 2 instances can not be deployed to the same k8s node.
https://github.com/couchbase-partners/helm-charts/blob/c53349e239b4438e6df413f993c8c944053ebc32/couchbase-operator/crds/couchbase.crds.yaml#L460-L461

Issue:
The helm template is missing this value so it is always set to `false`.
https://github.com/couchbase-partners/helm-charts/blob/c53349e239b4438e6df413f993c8c944053ebc32/couchbase-operator/templates/couchbase-cluster.yaml#L17-L22

Also, it is missing from the values
https://github.com/couchbase-partners/helm-charts/blob/c53349e239b4438e6df413f993c8c944053ebc32/couchbase-operator/values.yaml#L84

**Comment by 8tomat8** [comment]
The change is pretty simple so I can make the change. Do you accept PRs?

**Comment by tahmmee** [comment]
Thanks for pointing this out @8tomat8! Yes PRs accepted
