### ISSUE TITLE
Version disappeared from the Helm repo

### ISSUE THREAD

**Issue by 8tomat8** [couchbase-partners/helm-charts#18]
**Context:**
We are currently using the 2.0.1 version of the chart which was added 2 months ago [here](https://github.com/couchbase-partners/helm-charts/commit/8ab08836eda636c63fe8412b9313818c73b1e24c)

**Problem:**
The 2.0.1 is not available anymore
```bash
helm search repo -l couchbase/couchbase-operator
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                       
couchbase/couchbase-operator    2.0.1-001       2.0.1           A Helm chart to deploy the Couchbase Autonomous...
couchbase/couchbase-operator    2.0.0           2.0.0           A Helm chart to deploy the Couchbase Autonomous...
couchbase/couchbase-operator    0.1.2           1.2             A Helm chart to deploy the Couchbase Autonomous...
```

**Solution:**
Keep the historical releases for the backward compatibility.

**Comment by 8tomat8** [comment]
Thanks for the quick release though ;)

**Comment by tahmmee** [comment]
Yep It's back - sorry about that.
