### ISSUE TITLE
No way to create backup schedules with helm

### ISSUE THREAD

**Issue by 8tomat8** [couchbase-partners/helm-charts#20]
### Context
The operator helm chart has an option to enable backups for a cluster:
https://github.com/couchbase-partners/helm-charts/blob/758fef7e918ae3db21ee2543c535d7e97208abd9/couchbase-operator/values.yaml#L139-L146

Changing the value only schedules a task to keep track of the `CouchbaseBackup` resource (my assumption). But the resource itself has to be created using a raw k8s yaml.
Helm template for the resource is already there
https://github.com/couchbase-partners/helm-charts/blob/master/couchbase-operator/templates/couchbase-backup.yaml
But no way to define it using `values.yaml`

### Question
Are there any reasons not to enable it? Could it be related to the stability of the backups? https://github.com/couchbase-partners/helm-charts/issues/19

**Comment by tahmmee** [comment]
Right currently there is only backup enablement for the chart by creating the RBAC rules.  The actual scheduling tends to be a post-install step and didn't seem like fit for chart install.  Also, I assumed people will almost always customize schedule and perhaps want to do restores and so you'll likely end up with another raw k8s yaml with overrides somewhere.  It's same with XDCR Replications.

**Comment by tahmmee** [comment]
That said, we may eventually add it but there is no immediate plan.

**Comment by 8tomat8** [comment]
Okay, I've got your point, thank you. We will make some workaround for this :)
