### ISSUE TITLE
All the patched releases are considered `pre-releases`

### ISSUE THREAD

**Issue by 8tomat8** [couchbase-partners/helm-charts#21]
### Context:
The newly fixed versions of the helm chart are released with versions `2.0.1-001` and `2.0.2-01`.
When you search them using the helm command, you see that they are available:
```bash
# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "couchbase" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
# helm search repo -l couchbase/couchbase-operator
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                       
couchbase/couchbase-operator    2.0.1-001       2.0.1           A Helm chart to deploy the Couchbase Autonomous...
couchbase/couchbase-operator    2.0.1           2.0.1           A Helm chart to deploy the Couchbase Autonomous...
couchbase/couchbase-operator    2.0.0           2.0.0           A Helm chart to deploy the Couchbase Autonomous...
couchbase/couchbase-operator    0.1.2           1.2             A Helm chart to deploy the Couchbase Autonomous...
couchbase/couchbase-operator    2.0.2-01        2.0.2           A Helm chart to deploy the Couchbase Autonomous...
```

But if you try to pull or to install those releases, helm can not find them:
```bash
# helm pull couchbase/couchbase-operator --version 2.0.2-01
Error: chart "couchbase-operator" matching 2.0.2-01 not found in couchbase index. (try 'helm repo update'): constraint Parser Error

# helm pull couchbase/couchbase-operator --version 2.0.1-001
Error: chart "couchbase-operator" matching 2.0.1-001 not found in couchbase index. (try 'helm repo update'): constraint Parser Error
```

Trying to pull image which does not exist at all:
```bash
# helm pull couchbase/couchbase-operator --version 2.0.2    
Error: chart "couchbase-operator" matching 2.0.2 not found in couchbase index. (try 'helm repo update'): no chart version found for couchbase-operator-2.0.2
```

Existing version:
```bash
# helm pull couchbase/couchbase-operator --version 2.0.1
```

### Issue:
According to the Helm policies,  all the version tags with a dash separator after the semver the considered `pre-release` and can be installed only in develop mode (using --devel arg).
But when the `--devel` argument is user, `--version` is ignored, so if it is used in the production, with every new draft version helm will try to reinstall the CB.
Here is [an example](https://github.com/helm/helm/issues/5399). There are more in their repo :)

### Possible solutions:
1. Use another separator to identify "patched versions"
2. Detach `Chart version` from `App version`

### Workaround:
Go and manually clone the chart folder from the github repo and use the `couchbase-operator` folder instead of the remote repo.
**Don't forget to check the repo version** :smile:

**Comment by tahmmee** [comment]
Really hoping helm fixes this
```
when the --devel argument is user, --version is ignored, 
```

Here is what I'm planning then.  Going to release 2.0.2 version of the chart.
Then future patches will be pre-release of the next version.  ie 2.0.3-01, 2.0.3-02.... 2.0.3-NN.  
Then finally 2.0.3 will be published (matching 2.0.3-NN).

In a way helm hiding the dev version will help in case a PR causes breaking because only the major versions are considered stable.  Problem of course being that you can't use helm cli itself to install devel versions.

**Comment by 8tomat8** [comment]
I don't think they ever change it. It is a way to keep `--devel` argument for development only. Otherwise, people will abuse it quite soon :smile: 

I like the idea, it will give you the ability to test it and users can get their fixes asap. :+1: 
Do you have a release schedule, so we know when we can schedule updates accordingly?

**Comment by tahmmee** [comment]
There isn't an official release schedule, but we're targeting an approximate cycle of 6 months.

**Comment by 8tomat8** [comment]
Okay, thank you.
