### ISSUE TITLE
Prometheus-monitoring

### ISSUE THREAD

**Issue by LilaNKM** [couchbase-partners/helm-charts#28]
Hi,
Its a feature request.
Would it be possible to add support for Prometheus Monitoring with the inclusion of the service  and the  ServiceMonitor crd within the image of couchbase-exporter on the couchbase-operator chart :) ?

**Comment by tahmmee** [comment]
Yes, there is a monitoring stack which applies all of these resources, for example:
```
 helm install --set clusterName=my-cluster-name monitor couchbase/couchbase-monitor-stack 
```
See usage within context of autoscaling: https://docs.couchbase.com/operator/current/tutorial-autoscale.html#installing-a-monitoring-stack
