### ISSUE TITLE
operator fails when tls.generate=true

### ISSUE THREAD

**Issue by dash042** [couchbase-partners/helm-charts#31]
for a 2-node cluster - tls.generate generates the following error:

{"level":"info","ts":1611000474.2919781,"logger":"cluster","msg":"unable to update status","cluster":"default/cb-coop-0-couchbase-cluster","error":"admission webhook \"cb-coop-0-couchbase-admission-controller.default.svc\" denied the request: validation failure list:\ncertificate cannot be verified for zone: x509:
certificate is valid for localhost, *.cb-coop-0-couchbase-cluster.default.svc, *.cb-coop-0-couchbase-cluster.default, *.cb-coop-0-couchbase-cluster, *.cb-coop-0-couchbase-cluster-srv.default.svc, *.cb-coop-0-couchbase-cluster-srv.default, *.cb-coop-0-couchbase-cluster-srv, cb-coop-0-couchbase-cluster-srv.default.svc, cb-coop-0-couchbase-cluster-srv.default, cb-coop-0-couchbase-cluster-srv, *.cb-coop-0-couchbase-cluster-srv.default.svc.cluster.local, not host.cb-coop-0-couchbase-cluster.default.svc.cluster.local"}

**Comment by tahmmee** [comment]
Thanks @dash042 this is fixed.  Do `helm repo update` and try again
https://github.com/couchbase-partners/helm-charts/commit/2cea079684aeef7384159f69b0fc8b6d8dd42808
