### ISSUE TITLE
Sync Gateway Helm Chart Feature Request

### ISSUE THREAD

**Issue by lapellaniz** [couchbase-partners/helm-charts#32]
The Sync Gateway Helm chart requires a few additional features to be production ready:

1) Allow for additional pod labels to be set
2) Allow pod affinity settings to be set
3) Allow conditional configuration of admin 4985 ports to be exposed by the sync-gateway container
4) Allow container resource limits to be set
5) Allow conditional configuration of [Prometheus exporter](couchbasesamples/sync-gateway-prometheus-exporter:latest) container
5) Allow the service to expose additional ports such as 4985.

Some of this can be done for the operator and nodes but not sync gateway. I can submit a pull request with additional configuration to support this.

**Comment by tahmmee** [comment]
Thank you @lapellaniz!
Will certainly be looking into this as there is work being done for operator and admission controller to include additional settings/labels.  If you plan on contributing a PR for sync gateway that will be great!

**Comment by lapellaniz** [comment]
@tahmmee I opened a [PR](https://github.com/couchbase-partners/helm-charts/pull/34) with these changes.
