### ISSUE TITLE
Make default bucket optional

### ISSUE THREAD

**Issue by lapellaniz** [couchbase-partners/helm-charts#33]
Depending on the level of values.yaml files and charts used to deploy this helm-chart, there is an issue nulling out a section that is nested past 1 yaml file. Setting the following does not disable deploying the bucket if this chart is a subchart and multiple values.yaml files are used. There should be an easy way to exclude this bucket.

```yaml
buckets:
  default: null
```

**Comment by LordNoteworthy** [comment]
I confirm that setting `buckets.default: null` as per the doc does not work.

```yaml
# couchbase buckets to create
# disable default bucket creation by setting
buckets.default: null
```

Can anyone please have a look for this one.

**Comment by tahmmee** [comment]
Yes, there has been a fix addressing this:  https://github.com/couchbase-partners/helm-charts/commit/9e283f7c360991fda3055d5f778620cc9dbca2fd

Note the comment applies to doing  overrides via `--set buckets.default=null`  When doing yaml, it's
`
buckets:
  default: null
`
