### ISSUE TITLE
Anti-affinity for servers but not backups?

### ISSUE THREAD

**Issue by brigand** [couchbase-partners/helm-charts#36]
I can't tell from the docs or the source of the couchbase-operator chart if there's a supported way to have anti-affinity on the server pods (running couchbase server), but not on the backup/restore pods. They appear to reject each other and can cause backup jobs to be unschedulable (at 6 EKS nodes, 5 cb server pods, 1 cb operator pod, I can't schedule any backups).

Could you clarify how this is can be done, or if it can't currently, could it be implemented?

**Comment by tahmmee** [comment]
Right, currently not possible to do this since anti-affinity is applied cluster wide and can't be disabled for backup alone.  However, there is the option to apply node selectors and tolerations:
https://docs.couchbase.com/operator/current/reference-couchbasecluster.html#spec-backup

**Comment by tahmmee** [comment]
Closing. Hopefully selector on backup is working out. If this is desired specifically for backup then we can look into it as a feature.
