### ISSUE TITLE
cluster platform is missing in couchbase-operator helm chart

### ISSUE THREAD

**Issue by dewnull** [couchbase-partners/helm-charts#39]
I am using **couchbase-operator**  v2.1.011  to install CB on EKS and I get the following error for the console service load balancer:

` Error syncing load balancer: failed to ensure load balancer: unsupported load balancer affinity: ClientIP`

This is the same issue described in [Kubernetes Couchbase UI not assigned ELB in EKS throws error](https://forums.couchbase.com/t/kubernetes-couchbase-ui-not-assigned-elb-in-eks-throws-error/27125)

however, the helm chart doesn't allow to set  `cluster.platform: aws`
I tried to override the Session Affinity and set it to None using:
`cluster.networking.adminConsoleServiceTemplate.spec.sessionAffinity: "None"` but it seems that CB ignores it and I still sendup with `Session Affinity: ClientIP`

**Comment by sahnianuj** [comment]
Pull request #40 merged
