### ISSUE TITLE
Deprecation warning for Operator CRDs

### ISSUE THREAD

**Issue by dash042** [couchbase-partners/helm-charts#44]
I am getting errors deploying the latest version of the operator on AKS:

- apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
- admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
- admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration

**Comment by tahmmee** [comment]
Thanks! 2.1 does not officially support v1.22 although I'm sure it works there.  Will apply this for 2.2 release.
