### ISSUE TITLE
helm install results on readiness probe failing

### ISSUE THREAD

**Issue by LordNoteworthy** [couchbase-partners/helm-charts#85]
Hello,

Using the last version of the operator v2.3.001, doing a simple `helm install default couchbase/couchbase-operator` on a fresh k8s cluster (Client Version: v1.23.6, Server Version: v1.23.6) results on the pod being always stuck on non ready state. The readiness probes seems to fail.

![image](https://user-images.githubusercontent.com/5129564/168488070-46e7adbc-91ce-4ddf-8966-1d3421039075.png)

kubectl describe pods jupiter-0000:

```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  8m9s                    default-scheduler  Successfully assigned default/jupiter-0000 to node2
  Normal   Pulled     8m9s                    kubelet            Container image "couchbase/server:7.0.2" already present on machine
  Normal   Created    8m9s                    kubelet            Created container couchbase-server-init
  Normal   Started    8m9s                    kubelet            Started container couchbase-server-init
  Normal   Pulled     8m8s                    kubelet            Container image "couchbase/server:7.0.2" already present on machine
  Normal   Created    8m8s                    kubelet            Created container couchbase-server
  Normal   Started    8m8s                    kubelet            Started container couchbase-server
  Warning  Unhealthy  2m50s (x20 over 7m50s)  kubelet            Readiness probe failed: dial tcp 10.233.96.147:8091: connect: connection refused
```

Apparently, you are getting the same issue on github action while testing the chart using kind. The pod which contains the couchbase server never goes to ready state.

![image](https://user-images.githubusercontent.com/5129564/168487984-73cedce5-e176-4fc1-bcfa-70a00ad29e3a.png)

Can anyone have a look into this. Any help is much appreciated.

**Comment by tahmmee** [comment]
Hi @LordNoteworthy , I'm unable to reproduce this and haven't encountered this in recent testing, perhaps something else within the environment is causing this but I cannot tell from the status here.  Usually this message means the the Couchbase Service did not properly start for whatever reason.
Please share k8s cluster size and a log collection https://docs.couchbase.com/operator/current/tools/cao.html#cao-collect-logs-flags

**Comment by LordNoteworthy** [comment]
Thanks @tahmmee 

How do you run this tool ? I believe this tool is located inside the couchbase operator pod, but I am unable to attach to it. It seems like the docker image is stripped from sh and bash.

**Comment by tahmmee** [comment]
Right, the tool is included in the official Download: https://www.couchbase.com/downloads
Select: ("cloud-native database automation")

**Comment by LordNoteworthy** [comment]
I got that part, and I copied it inside the container in /tmp otherwise i got permission issues.

I am struggling to get inside the container.

**Comment by LordNoteworthy** [comment]
Hello @tahmmee I uploaded the cao logs [here](https://easyupload.io/yx6c9c).

Cheers.
